version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  
  catalogue:
    build:
      context: ./catalogue
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

  recco:
    build:
      context: ./recommendation
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  voting:
    build:
      context: ./voting
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
